# Default: SQLite setup (simple, no external database)
# For PostgreSQL: use docker-compose.postgres.yml

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - USE_SQLITE=1
    volumes:
      - ./backend:/app
      - media_volume:/app/media

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
      - REACT_APP_MEDIA_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  media_volume: